Add motu 360 k7ts nand support.  env_tools_linux_x86 comes from https://www.right.com.cn/forum/thread-8386060-1-1.html

diff --git a/initramfs/init b/initramfs/init
--- a/initramfs/init
+++ b/initramfs/init
@@ -168,9 +168,120 @@ if [ ! -e /original_mount_fail ]; then
     ln -s /original/usr/bin/nvram_get /bin/nvram_get
 fi
 
+#exit if sucess
+if [ ! -e /original_mount_fail ]; then
+    /bin/sh
+fi
+
+#p6c
+if [ -e /original/bin/nvram_get ]; then
+    ln -s /original/lib/ld-uClibc.so.0 /lib/ld-uClibc.so.0
+    ln -s /original/lib/libc.so.0  /lib/libc.so.0
+    ln -s /original/bin/nvram_get /bin/nvram_get
+    #exit if sucess
+    /bin/sh
+fi
+
+#motu_nand
+mtd_mount usr /original/usr/
+if [ $? -eq 1 ]; then
+    mtd_mount usr2 /original/usr/
+    if [ $? -eq 1 ]; then
+        echo "Mount original partition failed"
+        touch /original_nand_mount_fail
+    fi
+fi
+
+mtd_mount mix /original/mix/
+if [ $? -eq 1 ]; then
+    mtd_mount mix2 /original/mix/
+    if [ $? -eq 1 ]; then
+        echo "Mount original partition failed"
+        touch /original_nand_mount_fail
+    fi
+fi
+
+#exit if sucess
+if [ ! -e /original_nand_mount_fail ]; then
+    /bin/sh
+fi
 
 
+#motu_nand_ubi
+for i in 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20; do
+    busybox ubidetach /dev/ubi_ctrl -d "$i" 2>/dev/null
+done
 
+mtd_mount_ubi() {
+    local part_name="$1"
+    local mount_point="$2"
+
+    [ -z "$part_name" ] && return 1
+    [ -z "$mount_point" ] && return 1
+
+    local mtd_line
+    local mtd_num
+    local ubi_num
+    local vol_name
+
+    mtd_line=$(grep "\"$part_name\"" /proc/mtd)
+    [ -z "$mtd_line" ] && {
+        echo "MTD partition $part_name not found"
+        return 1
+    }
+
+    mtd_num=$(echo "$mtd_line" | cut -d: -f1 | sed 's/mtd//')
+
+    mkdir -p "$mount_point"
+
+    # Attach if not already attached
+    busybox ubiattach /dev/ubi_ctrl -m "$mtd_num"
+
+    ubi_vol=$(ls /dev/ubi*_? 2>/dev/null | busybox tail -1)
+    ubi_num=$(echo "$ubi_vol" | sed -n 's#/dev/ubi\([0-9]*\)_[0-9]*#\1#p')
+    [ -z "$ubi_vol" ] && return 1
+    [ -z "$ubi_num" ] && return 1
+
+
+    dd if="$ubi_vol" of=/tmp/"$part_name"
+    busybox ubidetach /dev/ubi_ctrl -d "$ubi_num"
+
+    # Mount by name
+    if mount /tmp/"$part_name" "$mount_point"; then
+        echo "Mounted UBI successfully"
+        return 0
+    fi
+
+
+    return 1
+}
+
+mtd_mount_ubi rootfs /original/
+if [ $? -eq 1 ]; then
+    mtd_mount_ubi rootfs2 /original/
+    if [ $? -eq 1 ]; then
+        echo "Mount original partition failed"
+        touch /original_nand_ubi_mount_fail
+    fi
+fi
+
+mtd_mount_ubi mix /original/mix/
+if [ $? -eq 1 ]; then
+    mtd_mount_ubi mix2 /original/mix/
+    if [ $? -eq 1 ]; then
+        echo "Mount original partition failed"
+        touch /original_nand_ubi_mount_fail
+    fi
+fi
+
+mtd_mount_ubi usr /original/usr/
+if [ $? -eq 1 ]; then
+    mtd_mount_ubi usr2 /original/usr/
+    if [ $? -eq 1 ]; then
+        echo "Mount original partition failed"
+        touch /original_nand_ubi_mount_fail
+    fi
+fi
 
 
 
